---
# Continuous Integration Workflow: Test case suite run + validation build check
name: CI

# Controls when the action will run.
# Triggers the workflow on push or pull request events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  # Job: Unit test suite
  unit-tests:
    name: "Unit Tests"
    runs-on: ubuntu-latest
    steps:
      # Install GCC 
      - name: Make Run Test
        run: |
          sudo apt-get install manpages-dev

      # Checks out repository under $GITHUB_WORKSPACE
      - name: Checkout Latest Repo
        uses: actions/checkout@v2

      # Run Tests
      - name: Make Run Test
        run: |
          make run-test
